title: Kenneth Steimel
description: Student of Computational Linguistics and High Performance Computing
show_downloads: false
google_analytics:
theme: jekyll-theme-modernist
categories: coffee programming cl infrastructure
